### ISSUE TITLE
[Bug]: Most of the custom models are not converted

### ISSUE THREAD

**Issue by Peppershade** [Kas-tle/java2bedrock.sh#1313]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/1312

### Expected Output

So, I'm using this tool to convert a resourcepack for GeyserMC which mainly includes models. But for some reason, 70-90% of the models are not converted. And I honestly don't know what's different between the working ones and not working ones. I did find the error below in the GitHub action.

I do have to say that I'm still very impressed by this converter, it's awesome.

### Actual Output

```
/home/runner/.config/yarn/global/node_modules/spritesheet-js/index.js:129
    if (err) throw err;
             ^

Error: Execution of identify command failed. Ensure that ImageMagick Legacy Tools are installed and added to your PATH.
    at /home/runner/.config/yarn/global/node_modules/spritesheet-js/lib/generator.js:52:28
    at ChildProcess.exithandler (node:child_process:406:5)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1090:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
```

After this it started spamming
`jq: Bad JSON in --slurpfile atlas scratch_files/spritesheet/145.json: Could not open scratch_files/spritesheet/145.json: No such file or directory`

**Comment by Kas-tle** [comment]
The texture `assets/minecraft/textures/block/bestel_fabula.png` is is causing the atlas generation to fail due to its extreme dimensions. There is a step meant to crop all animated texture images to the first frame, but this is failing due to the inability of `identify` to output anything for this image, so there is likely also an issue with the metadata of this file. Please remove this image or crop it and the converter should work fine. Do also keep in mind, however, that once this atlas is finally generated and included, this pack is likely to crash most bedrock clients, as it has dimensions of around 5400x. I would strongly recommend pre-cropping all high res textures in the pack to the minimum size that is acceptable to you. I am now closing this as this is largely an issue with the input and not the converter. Please use the discussions section for further help with conversion.

![145](https://user-images.githubusercontent.com/26531652/199660451-7839472a-875a-426a-83df-035ca096e264.png)

![bestel_fabula](https://user-images.githubusercontent.com/26531652/199659626-a51bf7fd-6e2d-43f2-9ba5-69893882e772.png)
