### ISSUE TITLE
[Bug]: .mcpack crashes launcher

### ISSUE THREAD

**Issue by benatkinson-dev** [Kas-tle/java2bedrock.sh#1917]
### Conversion Issue Link

https://github.com/Kas-tle/java2bedrock.sh/issues/1916#event-7946568156

### Expected Output

Launcher to load as expected and custom items to be displayed.

### Actual Output

Convertor was working perfectly and no issues were present, now when attempting to load into a world or server using the converted pack it crashes the launcher, This has only started happening since 1.19.50

**Comment by Toxijello** [comment]
Shoot, I have this issue. Thought I did something wrong, given I was doing it while being awake for 26 hours straight, guess not...

**Comment by benatkinson-dev** [comment]
I guess that the 1.19.50 update has broken something, that or were both causing the same issue 😅

**Comment by Kas-tle** [comment]
Hello, thank you for the issue.

This was unrelated to the 1.19.50 update. It seems that Github has changed the behavior of menus on issue forms. Before, if no options were selected, the submitted issue would read `*No Response*` for any slider based questions, as it still does when no response is given to a text based question. Instead, it now default selects `None`. Since this did not match `*No Response*`, it was causing `None` to be used as the attachable's material. On desktop, this generally only leads to a content log error. On some platforms, however, this can cause a crash.

I have [rerun](https://github.com/Kas-tle/java2bedrock.sh/issues/1922) your conversion with the updated action and it seems to produce a valid pack used on a Geyser server with a 1.19.50 client.

![image](https://user-images.githubusercontent.com/26531652/205464243-1cae006a-c63c-457c-9a35-f156e6bd346a.png)
[Pack Files.zip](https://github.com/Kas-tle/java2bedrock.sh/files/10147470/Pack.Files.zip)

**Comment by benatkinson-dev** [comment]
> Hello, thank you for the issue.
> 
> This was unrelated to the 1.19.50 update. It seems that Github has changed the behavior of menus on issue forms. Before, if no options were selected, the submitted issue would read `*No Response*` for any slider based questions, as it still does when no response is given to a text based question. Instead, it now default selects `None`. Since this did not match `*No Response*`, it was causing `None` to be used as the attachable's material. On desktop, this generally only leads to a content log error. On some platforms, however, this can cause a crash.
> 
> I have [rerun](https://github.com/Kas-tle/java2bedrock.sh/issues/1922) your conversion with the updated action and it seems to produce a valid pack used on a Geyser server with a 1.19.50 client.
> 
> ![image](https://user-images.githubusercontent.com/26531652/205464243-1cae006a-c63c-457c-9a35-f156e6bd346a.png) [Pack Files.zip](https://github.com/Kas-tle/java2bedrock.sh/files/10147470/Pack.Files.zip)

Thank you! can confirm it worked for me as well, glad it wasn't to serious
